services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    volumes:
      # Mount the entire project directory to persist config, session, and log files
      - ./:/app
      # Mount the .env file explicitly
      - ./.env:/app/.env  
    environment:
      # Ensure the container can read the .env file
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'python main_bot.py' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
